#ifndef BOSERCN_H
#define BOSERCN_H

#include "bosercn.windef.h"

#define BOSERCN_EXT_API
#define BOSERCN_EXPORT

#ifdef __cplusplus
extern "C"
{
#define DEFVAL(x) = x
#else
#define DEFVAL(x)
#endif

// RESULT OF FUNCTION
//
typedef enum {

	BOSERCN_RS_SUCCESSFUL								= 0x00000000,

	BOSERCN_RS_ERROR_GENERAL							= 0x00000001,

	BOSERCN_RS_ERROR_OUT_OF_MEMORY						= 0x00000002,

	BOSERCN_RS_ERROR_OUT_OF_RESOURCE					= 0x00000003,

	BOSERCN_RS_ERROR_INVALID_DEVICE						= 0x00000004,

	BOSERCN_RS_ERROR_INVALID_PARAMETER					= 0x00000005,

	BOSERCN_RS_ERROR_NON_SUPPORT						= 0x00000006,

	BOSERCN_RS_ERROR_TIMEOUT							= 0x00000007,

	BOSERCN_RS_ERROR_INVALID_ANIMATION_SCRIPT			= 0x00000008,

	BOSERCN_RS_ERROR_NO_SIGNAL_DETECTED					= 0x00000009,

	BOSERCN_RS_ERROR_NEED_MORE_DATA						= 0x0000000A,

	BOSERCN_RS_ERROR_CONNECT_FAIL						= 0x0000000B,

	BOSERCN_RS_ERROR_FILE_ACCESS_FAIL					= 0x0000000C,

	BOSERCN_RS_ERROR_NETWORK_ACCESS_FAIL				= 0x0000000D,

	BOSERCN_RS_ERROR_FILE_IS_BOX_MOVED					= 0x0000000E,

	BOSERCN_RS_ERROR_FRAME_IS_COPIED					= 0x0000000F,

	BOSERCN_RS_ERROR_VIDEO_ENCODER_ACCESS_FAIL			= 0x00000010,

	BOSERCN_RS_ERROR_AUDIO_ENCODER_ACCESS_FAIL			= 0x00000011,

	BOSERCN_RS_ERROR_NETWORK_CONNECT_UNKNOWN_FAIL		= 0x80000000,

	BOSERCN_RS_ERROR_NETWORK_CONNECT_URL_FAIL			= 0x80000001,

	BOSERCN_RS_ERROR_NETWORK_CONNECT_PASSWORD_FAIL		= 0x80000002,

	BOSERCN_RS_ERROR_NETWORK_CONNECT_SESSION_NAME_FAIL = 0x80000003,

} BRESULT;

// RETURN OF CALLBACK
//
typedef enum {

	BOSERCN_RT_OK					= 0x00000000,
	
	BOSERCN_RT_FAIL					= 0x00000001,

	BOSERCN_RT_SKIP_RECORD_NUM_00	= 0x00010002, // ONLY FOR PF_VIDEO_PREVIEW_CALLBACK / PF_AUDIO_PREVIEW_CALLBACK

	BOSERCN_RT_SKIP_RECORD_NUM_01	= 0x00020002, // ONLY FOR PF_VIDEO_PREVIEW_CALLBACK / PF_AUDIO_PREVIEW_CALLBACK

	BOSERCN_RT_SKIP_RECORD_NUM_02	= 0x00040002, // ONLY FOR PF_VIDEO_PREVIEW_CALLBACK / PF_AUDIO_PREVIEW_CALLBACK

	BOSERCN_RT_SKIP_RECORD_NUM_03	= 0x00080002, // ONLY FOR PF_VIDEO_PREVIEW_CALLBACK / PF_AUDIO_PREVIEW_CALLBACK

	BOSERCN_RT_SKIP_DISPLAY			= 0x00000004, // ONLY FOR PF_VIDEO_PREVIEW_CALLBACK / PF_AUDIO_PREVIEW_CALLBACK / 
											  //
											  //		  PF_VIDEO_BROADCAST_CLIENT_CALLBACK / PF_AUDIO_BROADCAST_CLIENT_CALLBACK / 
											  //
											  //		  PF_VIDEO_DECODER_BROADCAST_CLIENT_CALLBACK / PF_AUDIO_DECODER_BROADCAST_CLIENT_CALLBACK /
											  //
											  //		  PF_VIDEO_DECODER_FILE_CALLBACK / PF_AUDIO_DECODER_FILE_CALLBACK
											  
	BOSERCN_RT_SKIP_CLONE_DISPLAY	= 0x00000008, // ONLY FOR PF_VIDEO_PREVIEW_CALLBACK / PF_AUDIO_PREVIEW_CALLBACK

	BOSERCN_RT_RESET_RECORD_NUM_00	= 0x01000010, // ONLY FOR PF_VIDEO_PREVIEW_CALLBACK / PF_AUDIO_PREVIEW_CALLBACK

	BOSERCN_RT_RESET_RECORD_NUM_01	= 0x02000010, // ONLY FOR PF_VIDEO_PREVIEW_CALLBACK / PF_AUDIO_PREVIEW_CALLBACK

	BOSERCN_RT_RESET_RECORD_NUM_02	= 0x04000010, // ONLY FOR PF_VIDEO_PREVIEW_CALLBACK / PF_AUDIO_PREVIEW_CALLBACK

	BOSERCN_RT_RESET_RECORD_NUM_03	= 0x08000010, // ONLY FOR PF_VIDEO_PREVIEW_CALLBACK / PF_AUDIO_PREVIEW_CALLBACK

} BRETURN;

// INPUT VIDEO SOURCE
//
enum {

	BOSERCN_INPUT_TYPE_COMPOSITE	 = 0,

	BOSERCN_INPUT_TYPE_SVIDEO		 = 1,

	BOSERCN_INPUT_TYPE_HDMI		 = 2,

	BOSERCN_INPUT_TYPE_DVI_D		 = 3,

	BOSERCN_INPUT_TYPE_COMPONENTS	 = 4,

	BOSERCN_INPUT_TYPE_YCBCR		 = 4,

	BOSERCN_INPUT_TYPE_DVI_A		 = 5,

	BOSERCN_INPUT_TYPE_RGB			 = 5,

	BOSERCN_INPUT_TYPE_VGA			 = 5,

	BOSERCN_INPUT_TYPE_SDI			 = 6,

	BOSERCN_INPUT_TYPE_DISPLAY_PORT = 8,

	BOSERCN_INPUT_TYPE_AUTO		 = 7,
};

// INPUT AUDIO SOURCE
//
enum {	

	BOSERCN_INPUT_TYPE_EMBEDDED_AUDIO			= 0,

	BOSERCN_INPUT_TYPE_LINE_IN					= 1,

	BOSERCN_INPUT_TYPE_SOUNDCARD_MICROPHONE	= 2,

	BOSERCN_INPUT_TYPE_SOUNDCARD_LINE_IN		= 3,
};

// VIDEO STANDARD TYPE
//
enum {	

	BOSERCN_STANDARD_TYPE_NTSC_M		= 0x00000001,

	BOSERCN_STANDARD_TYPE_NTSC_M_J		= 0x00000002,

	BOSERCN_STANDARD_TYPE_NTSC_433		= 0x00000004,

	BOSERCN_STANDARD_TYPE_PAL_M		= 0x00000200,

	BOSERCN_STANDARD_TYPE_PAL_60		= 0x00000800,

	BOSERCN_STANDARD_TYPE_PAL_B		= 0x00000010,

	BOSERCN_STANDARD_TYPE_PAL_D		= 0x00000020,

	BOSERCN_STANDARD_TYPE_PAL_G		= 0x00000040,

	BOSERCN_STANDARD_TYPE_PAL_H		= 0x00000080,

	BOSERCN_STANDARD_TYPE_PAL_I		= 0x00000100,

	BOSERCN_STANDARD_TYPE_PAL_N		= 0x00000400,

	BOSERCN_STANDARD_TYPE_PAL_N_COMBO	= 0x00100000,

	BOSERCN_STANDARD_TYPE_AUTO			= 0x80000000, // DEFAULT, [P.S. SC310N8/N16            (CX2581 PCI) DON'T SUPPORT AUTO STANDARD DETECTION]
												  //
												  //		  [P.S. SC290N4/SC390N4/N8/N16 (AH8400 PCI) DON'T SUPPORT AUTO STANDARD DETECTION]
												  //
												  //		  [P.S. SC2B0N4/SC3B0N4/N8/N16 (TW5864 PCI) DON'T SUPPORT AUTO STANDARD DETECTION]
												  //
												  //		  [P.S. SC3A0N4/N8/N16         (FH8735 PCI) DON'T SUPPORT AUTO STANDARD DETECTION]
												  //
												  //		  [P.S. SC3C0N4/N8/N16         (MZ0380 PCI) DON'T SUPPORT AUTO STANDARD DETECTION]
};

// VIDEO DEINTERLACE TYPE
//
enum {	

	BOSERCN_SOFTWARE_DEINTERLACE_TYPE_BLENDING			  = 0x00000000, // DEFAULT

	BOSERCN_SOFTWARE_DEINTERLACE_TYPE_MOTIONAD_APTIVE	  = 0x00000001,

	BOSERCN_SOFTWARE_DEINTERLACE_TYPE_FILTER_TRIANGLE	  = 0x00000002,

	BOSERCN_SOFTWARE_DEINTERLACE_TYPE_BOB				  = 0x00000003,

	BOSERCN_SOFTWARE_DEINTERLACE_TYPE_MEDICAL_RGB_REPACK = 0x00000010, // DEVELOPING ...
};

// COLORRANGE TYPE
//
enum {

	BOSERCN_COLORRANGE_TYPE_FULL		 = 0, //  0 ~ 255

	BOSERCN_COLORRANGE_TYPE_LIMIT		 = 1, // 16 ~ 235

	BOSERCN_COLORRANGE_TYPE_FULL_BGR32	 = 2, //  0 ~ 255 (RENDERER @ RGB32)

	BOSERCN_COLORRANGE_TYPE_LIMIT_BGR32 = 3, // 16 ~ 235 (RENDERER @ RGB32)
};

// COLORSPACE TYPE
//
enum {

	BOSERCN_COLORSPACE_TYPE_RGB24	= 0,		  //   0xBBGGRR -> R0 G0 B0 R1 G1 B1 R2 G2 B2 ... >>

	BOSERCN_COLORSPACE_TYPE_BGR24	= 1,		  //   0xRRGGBB -> B0 G0 R0 B1 G1 R1 B2 G2 R2 ... >>

	BOSERCN_COLORSPACE_TYPE_ARGB32	= 2,		  // 0xAABBGGRR -> R0 G0 B0 A0 R1 G1 B1 A1 R2 G2 B2 A2 ... >>

	BOSERCN_COLORSPACE_TYPE_ABGR32	= 3,		  // 0xAARRGGBB -> B0 G0 R0 A0 B1 G1 R1 A1 B2 G2 R2 A2 ... >>

	BOSERCN_COLORSPACE_TYPE_YUY2	= 0x32595559, // 0x32595559 -> MAKEFOURCC('Y', 'U', 'Y', '2')

	BOSERCN_COLORSPACE_TYPE_UYVY	= 0x59565955, // 0x59565955 -> MAKEFOURCC('U', 'Y', 'V', 'Y')

	BOSERCN_COLORSPACE_TYPE_YV12	= 0x32315659, // 0x32315659 -> MAKEFOURCC('Y', 'V', '1', '2') (Y V U)

	BOSERCN_COLORSPACE_TYPE_I420	= 0x30323449, // 0x30323449 -> MAKEFOURCC('I', '4', '2', '0') -> Y U V

	BOSERCN_COLORSPACE_TYPE_Y800	= 0x30303859, // 0x30303859 -> MAKEFOURCC('Y', '8', '0', '0') -> Y

	BOSERCN_COLORSPACE_TYPE_MJPG	= 0x47504A4D, // 0x47504A4D -> MAKEFOURCC('M', 'J', 'P', 'G')

	BOSERCN_COLORSPACE_TYPE_H264	= 0x34363248, // 0x34363248 -> MAKEFOURCC('H', '2', '6', '4')

	BOSERCN_COLORSPACE_TYPE_H265	= 0x35363248, // 0x34363248 -> MAKEFOURCC('H', '2', '6', '5')
};

// ENCODER TYPE (RECORD PROPERTY)
//
enum {

	BOSERCN_ENCODER_TYPE_SOFTWARE			= 0,

	BOSERCN_ENCODER_TYPE_HARDWARE			= 1, // IT IS ONLY USED FOR HARDWARE COMPRESSION CAPTURE CARD, SUCH AS SC580 & SC590 & SC5A0 & SC5C0

	BOSERCN_ENCODER_TYPE_INTEL_MEDIA_SDK	= 2,

	BOSERCN_ENCODER_TYPE_AMD_VCE			= 3,

	BOSERCN_ENCODER_TYPE_NVIDIA_CUDA		= 4,

	BOSERCN_ENCODER_TYPE_NVIDIA_NVENC		= 5,
};

// ENCODER VIDEO FORMAT (RECORD PROPERTY)
//
enum {

	BOSERCN_ENCODER_FORMAT_MPEG2		=  1,

	BOSERCN_ENCODER_FORMAT_H264		=  0,

	BOSERCN_ENCODER_FORMAT_H264_3D		=  2, // H264 MVC (STEREOSCOPIC 3D)

	BOSERCN_ENCODER_FORMAT_H264_VC		=  3, // H264 SVC (MULTIPLE TEMPORAL SCALABILITY)

	BOSERCN_ENCODER_FORMAT_RAW			=  4,

	BOSERCN_ENCODER_FORMAT_RAW_NATIVE	=  4,

	BOSERCN_ENCODER_FORMAT_H265		=  5,

	BOSERCN_ENCODER_FORMAT_RAW_YUY2	= 20,

	BOSERCN_ENCODER_FORMAT_RAW_UYVY	= 21, // DEVELOPING ...

	BOSERCN_ENCODER_FORMAT_RAW_YV12	= 22,

	BOSERCN_ENCODER_FORMAT_RAW_I420	= 23, // DEVELOPING ...

	BOSERCN_ENCODER_FORMAT_RAW_Y800	= 24,
};

// ENCODER AUDIO FORMAT (RECORD PROPERTY)
//
enum {

	BOSERCN_ENCODER_FORMAT_PCM			= 0,

	BOSERCN_ENCODER_FORMAT_AAC			= 1,

	BOSERCN_ENCODER_FORMAT_AAC_RAW		= 1,

	BOSERCN_ENCODER_FORMAT_AAC_ADTS	= 2,

	BOSERCN_ENCODER_FORMAT_MP2			= 4, // MPEG AUDIO LAYER 2

	BOSERCN_ENCODER_FORMAT_MP3			= 5, // MPEG AUDIO LAYER 3

	BOSERCN_ENCODER_FORMAT_OPUS		= 6,

	BOSERCN_ENCODER_FORMAT_AC3			= 7,
};

// RECORD PROFILE (RECORD PROPERTY)
//
enum {

	BOSERCN_RECORD_PROFILE_BASELINE	         = 0, // DEFAULT

	BOSERCN_RECORD_PROFILE_MAIN		         = 1,

	BOSERCN_RECORD_PROFILE_HIGH		         = 2,

	BOSERCN_RECORD_PROFILE_CONSTRAINED_BASELINE = 3, // ONLY FOR BOSERCN_ENCODER_FORMAT_H264_VC

	BOSERCN_RECORD_PROFILE_CONSTRAINED_HIGH     = 4, // ONLY FOR BOSERCN_ENCODER_FORMAT_H264_VC
};

// RECORD LEVEL (RECORD PROPERTY)
//
enum {

	BOSERCN_RECORD_LEVEL_1		= 10,

	BOSERCN_RECORD_LEVEL_1B	=  9,

	BOSERCN_RECORD_LEVEL_11	= 11,

	BOSERCN_RECORD_LEVEL_12	= 12,

	BOSERCN_RECORD_LEVEL_13	= 13,

	BOSERCN_RECORD_LEVEL_2		= 20,

	BOSERCN_RECORD_LEVEL_21	= 21,

	BOSERCN_RECORD_LEVEL_22	= 22,

	BOSERCN_RECORD_LEVEL_3		= 30,

	BOSERCN_RECORD_LEVEL_31	= 31,

	BOSERCN_RECORD_LEVEL_32	= 32,

	BOSERCN_RECORD_LEVEL_4		= 40,

	BOSERCN_RECORD_LEVEL_41	= 41, // DEFAULT

	BOSERCN_RECORD_LEVEL_42	= 42,

	BOSERCN_RECORD_LEVEL_50	= 50,

	BOSERCN_RECORD_LEVEL_51	= 51,

	BOSERCN_RECORD_LEVEL_52	= 52,

	BOSERCN_RECORD_LEVEL_60	= 60,

	BOSERCN_RECORD_LEVEL_61	= 61,

	BOSERCN_RECORD_LEVEL_62	= 62,
};

// RECORD ENTROPY (RECORD PROPERTY)
//
enum {

	BOSERCN_RECORD_ENTROPY_CAVLC	= 0, // DEFAULT

	BOSERCN_RECORD_ENTROPY_CABAC	= 1,
};

// RECORD COMPLEXITY (RECORD PROPERTY)
//
enum {

	BOSERCN_RECORD_COMPLEXITY_0	= 0, // BEST SPEED, DEFAULT

	BOSERCN_RECORD_COMPLEXITY_1	= 1,

	BOSERCN_RECORD_COMPLEXITY_2	= 2,

	BOSERCN_RECORD_COMPLEXITY_3	= 3,

	BOSERCN_RECORD_COMPLEXITY_4	= 4,

	BOSERCN_RECORD_COMPLEXITY_5	= 5,

	BOSERCN_RECORD_COMPLEXITY_6	= 6, // BEST QUALITY
};

// RECORD MODE (RECORD PROPERTY)
//
enum {

	BOSERCN_RECORD_MODE_VBR		= 0, 

	BOSERCN_RECORD_MODE_CBR		= 1, 

	BOSERCN_RECORD_MODE_ABR		= 2, 

	BOSERCN_RECORD_MODE_CQP		= 3, // DEVELOPING ...

	BOSERCN_RECORD_MODE_LOSSLESS	= 4, 
};

// DOWNSCALE MODE (RECORD PROPERTY)
// 
enum {

	BOSERCN_DOWNSCALE_MODE_OFF	= 0, // (1920, 1080) * (1 / 1) = (1920, 1080)

	BOSERCN_DOWNSCALE_MODE_2_3	= 1, // (1920, 1080) * (2 / 3) = (1280,  720)

	BOSERCN_DOWNSCALE_MODE_1_2	= 2, // (1920, 1080) * (1 / 2) = ( 960,  540)

	BOSERCN_DOWNSCALE_MODE_1_4	= 3, // (1920, 1080) * (1 / 4) = ( 480,  270)
};

// RECORD FLAG (RECORD PROPERTY)
//
enum {

	BOSERCN_RECORD_FLAG_FULL						= 0x00000007,

	BOSERCN_RECORD_FLAG_FILE						= 0x00000001,

	BOSERCN_RECORD_FLAG_ENCODE						= 0x00000002,

	BOSERCN_RECORD_FLAG_DISPLAY					= 0x00000004,

	BOSERCN_RECORD_FLAG_DECODE						= 0x00000008,

	BOSERCN_RECORD_FLAG_VIDEO_ONLY					= 0x00000010,

	BOSERCN_RECORD_FLAG_AUDIO_ONLY					= 0x00000020,

	BOSERCN_RECORD_FLAG_VIDEO_USE_IDEAL_TIMESTAMP	= 0x00000040,

	BOSERCN_RECORD_FLAG_AUDIO_USE_IDEAL_TIMESTAMP	= 0x00000080,

	BOSERCN_RECORD_FLAG_INGNORE_FORMAT_CHANGED		= 0x00000100,

	BOSERCN_RECORD_FLAG_SYNCHRONIZED_RECORD		= 0x00000200, // START BY BOSERCN_RESUME_RECORD

	BOSERCN_RECORD_FLAG_VIDEO_USE_MEDIA_TIMER		= 0x00000400, // ONLY FOR BOSERCN_SET_VIDEO_*_UNCOMPRESSION_BUFFER_*

	BOSERCN_RECORD_FLAG_AUDIO_USE_MEDIA_TIMER		= 0x00000800, // ONLY FOR BOSERCN_SET_AUDIO_*_UNCOMPRESSION_BUFFER_*
};

// BROADCAST FLAG (BROADCAST PROPERTY)
//
enum {

	BOSERCN_BROADCAST_FLAG_FULL						= 0x00000007,

	BOSERCN_BROADCAST_FLAG_NETWORK						= 0x00000001,

	BOSERCN_BROADCAST_FLAG_ENCODE						= 0x00000002,

	BOSERCN_BROADCAST_FLAG_DISPLAY						= 0x00000004,

	BOSERCN_BROADCAST_FLAG_DECODE						= 0x00000008,

	BOSERCN_BROADCAST_FLAG_VIDEO_ONLY					= 0x00000010,
	
	BOSERCN_BROADCAST_FLAG_AUDIO_ONLY					= 0x00000020,

	BOSERCN_BROADCAST_FLAG_VIDEO_USE_IDEAL_TIMESTAMP	= 0x00000040,

	BOSERCN_BROADCAST_FLAG_AUDIO_USE_IDEAL_TIMESTAMP	= 0x00000080,

	BOSERCN_BROADCAST_FLAG_VIDEO_USE_MEDIA_TIMER		= 0x00000400, // ONLY FOR BOSERCN_SET_VIDEO_*_UNCOMPRESSION_BUFFER_*

	BOSERCN_BROADCAST_FLAG_AUDIO_USE_MEDIA_TIMER		= 0x00000800, // ONLY FOR BOSERCN_SET_AUDIO_*_UNCOMPRESSION_BUFFER_*
};

// BROADCAST PROTOCOL (BROADCAST PROPERTY)
//
enum {

	BOSERCN_BROADCAST_PROTOCOL_UDP	 = 0x00000000,

	BOSERCN_BROADCAST_PROTOCOL_TCP	 = 0x00000001, // BPS >= 12MBPS, SUGGEST TO SUE BOSERCN_BROADCAST_PROTOCOL_TCP

	BOSERCN_BROADCAST_PROTOCOL_HTTP = 0x00000002,
};

// OSD FONT STYLE (OSD PROPERTY)
//
enum {

    BOSERCN_FONT_STYLE_REGULAR     = 0x00000000,
    
	BOSERCN_FONT_STYLE_BOLD        = 0x00000001,
    
	BOSERCN_FONT_STYLE_ITALIC      = 0x00000002,
    
	BOSERCN_FONT_STYLE_BOLDITALIC  = 0x00000003,
    
	BOSERCN_FONT_STYLE_UNDERLINE   = 0x00000004,
    
	BOSERCN_FONT_STYLE_STRIKEOUT   = 0x00000008,
};

// OSD STRING ALIGNMENT (OSD PROPERTY)
//
enum {

	BOSERCN_STRING_ALIGNMENT_STYLE_LEFT    = 0x00000000,

    BOSERCN_STRING_ALIGNMENT_STYLE_NEAR    = 0x00000000,
    
	BOSERCN_STRING_ALIGNMENT_STYLE_CENTER  = 0x00000001,
    
	BOSERCN_STRING_ALIGNMENT_STYLE_RIGHT   = 0x00000002,
    
	BOSERCN_STRING_ALIGNMENT_STYLE_FAR		= 0x00000002,
};

// OSD SEQUENCE STYLE (OSD PROPERTY)
//
enum {

	//  GENERAL DEVICE: FOREMOST -> PREVIEW CALLBACK -> BEFORE_ENCODE -> RECORDING (ENCODING) -> AFTERMOST
	//
	// SHARE RECORDING: FOREMOST -> RECORDING (ENCODING) -> AFTERMOST
	//
	// SHARE STREAMING: FOREMOST -> STREAMING (ENCODING) -> AFTERMOST
	//
	//  VIRTUAL CAMERA: FOREMOST -> AFTERMOST -> SHARING
	//
	//   FILE PLAYBACK: PLAYBACK (DECODING) -> FOREMOST -> DECODER CALLBACK -> AFTERMOST
	//
	BOSERCN_SEQUENCE_STYLE_FOREMOST		= 0x00000000,

    BOSERCN_SEQUENCE_STYLE_BEFORE_ENCODE	= 0x00000001, // IT IS ONLY USED FOR GENERAL DEVICE
    
	BOSERCN_SEQUENCE_STYLE_AFTERMOST		= 0x00000002,
};

// BUFFER SCALE STYLE (BUFFER PROPERTY)
//
enum {

	BOSERCN_SCALE_STYLE_STRETCH	= 0x00000000,

    BOSERCN_SCALE_STYLE_FIT		= 0x00000001,
    
	BOSERCN_SCALE_STYLE_FILL		= 0x00000002,
};

// DECODER TYPE (PLAYBACK PROPERTY)
//
enum {

	BOSERCN_DECODER_TYPE_SOFTWARE			= 0,

	BOSERCN_DECODER_TYPE_HARDWARE			= 1, // DEVELOPING ...

	BOSERCN_DECODER_TYPE_INTEL_MEDIA_SDK	= 2,

	BOSERCN_DECODER_TYPE_AMD_UVD			= 3, // DEVELOPING ...

	BOSERCN_DECODER_TYPE_AMD_VCE			= 3, // == BOSERCN_DECODER_TYPE_AMD_UVD

	BOSERCN_DECODER_TYPE_NVIDIA_CUDA		= 4,

	BOSERCN_DECODER_TYPE_NVIDIA_NVDEC		= 5,

	BOSERCN_DECODER_TYPE_NVIDIA_NVENC		= 5, // == BOSERCN_DECODER_TYPE_NVIDIA_NVDEC
};

// DECODER VIDEO FORMAT (PLAYBACK PROPERTY)
//
enum {

	BOSERCN_DECODER_FORMAT_MPEG2		=  1,

	BOSERCN_DECODER_FORMAT_H264		=  0,

	BOSERCN_DECODER_FORMAT_H264_3D		=  2, // H264 MVC (STEREOSCOPIC 3D)

	BOSERCN_DECODER_FORMAT_H264_VC		=  3, // H264 SVC (MULTIPLE TEMPORAL SCALABILITY)

	BOSERCN_DECODER_FORMAT_RAW			=  4,

	BOSERCN_DECODER_FORMAT_H265		=  5,
};

// 3D STEREO BUFFER TYPE
//
enum {

	BOSERCN_3D_STEREO_BUFFER_SIDE_BY_SIDE		= 0,

	BOSERCN_3D_STEREO_BUFFER_TOP_BOTTOM		= 1,

	BOSERCN_3D_STEREO_BUFFER_LINE_BY_LINE		= 2,
};

// 3D STEREO DISPLAY MODE
//
enum {

	BOSERCN_3D_STEREO_DISPLAY_MODE_SIDE_BY_SIDE	= 0,

	BOSERCN_3D_STEREO_DISPLAY_MODE_TOP_BOTTOM		= 1,

	BOSERCN_3D_STEREO_DISPLAY_MODE_LINE_BY_LINE	= 2,

	BOSERCN_3D_STEREO_DISPLAY_MODE_LEFT_ONLY		= 3,

	BOSERCN_3D_STEREO_DISPLAY_MODE_RIGHT_ONLY		= 4,
};

// FILE TIMEUNIT
//
enum {

	BOSERCN_FILE_TIMEUNIT_TIME		= 0,

	BOSERCN_FILE_TIMEUNIT_FRAME	= 1,
};

// SERIAL PORT PARITY CHECK (SERIAL PORT PROPERTY)
//
enum {

	BOSERCN_SERIAL_PORT_PARITY_CHECK_NONE	= 0x00000000,

	BOSERCN_SERIAL_PORT_PARITY_CHECK_ODD	= 0x00000001,

	BOSERCN_SERIAL_PORT_PARITY_CHECK_EVEN	= 0x00000002,

	BOSERCN_SERIAL_PORT_PARITY_CHECK_MARK	= 0x00000003,		

	BOSERCN_SERIAL_PORT_PARITY_CHECK_SPACE	= 0x00000004,
};

// SERIAL PORT FLOW CONTROL (SERIAL PORT PROPERTY)
//
enum {

	BOSERCN_SERIAL_PORT_FLOW_CONTROL_NONE		= 0x00000000,

	BOSERCN_SERIAL_PORT_FLOW_CONTROL_CTS_RTS	= 0x00000001,

	BOSERCN_SERIAL_PORT_FLOW_CONTROL_CTS_DTR	= 0x00000002,

	BOSERCN_SERIAL_PORT_FLOW_CONTROL_DSR_RTS	= 0x00000003,

	BOSERCN_SERIAL_PORT_FLOW_CONTROL_DSR_DTR	= 0x00000004,

	BOSERCN_SERIAL_PORT_FLOW_CONTROL_XON_XOFF	= 0x00000005,
};

// SERIAL PORT STOP BITS (SERIAL PORT PROPERTY)
//
enum {

	BOSERCN_SERIAL_PORT_STOP_BITS_ONE				= 0x00000000,

	BOSERCN_SERIAL_PORT_STOP_BITS_ONE_POINT_FIVE	= 0x00000001,

	BOSERCN_SERIAL_PORT_STOP_BITS_TWO				= 0x00000002,
};

// SERIAL PORT SIGNAL TYPE (SERIAL PORT PROPERTY)
//
enum {

	BOSERCN_SERIAL_PORT_SIGNAL_TYPE_CLEAR_DTR		= 0x00000000, // CLEAR THE DTR (DATA-TERMINAL-READY) SIGNAL

	BOSERCN_SERIAL_PORT_SIGNAL_TYPE_CLEAR_RTS		= 0x00000001, // CLEAR THE RTS (REQUEST-TO-SEND) SIGNAL

	BOSERCN_SERIAL_PORT_SIGNAL_TYPE_SET_DTR		= 0x00000002, // SEND THE DTR (DATA-TERMINAL-READY) SIGNAL

	BOSERCN_SERIAL_PORT_SIGNAL_TYPE_SET_RTS		= 0x00000003, // SEND THE RTS (REQUEST-TO-SEND) SIGNAL

	BOSERCN_SERIAL_PORT_SIGNAL_TYPE_SET_XOFF		= 0x00000004, // CAUSE TRANSMISSION TO ACT AS IF AN XOFF CHARACTER HAS BEEN RECEIVED

	BOSERCN_SERIAL_PORT_SIGNAL_TYPE_SET_XON		= 0x00000005, // CAUSE TRANSMISSION TO ACT AS IF AN XON CHARACTER HAS BEEN RECEIVED

	BOSERCN_SERIAL_PORT_SIGNAL_TYPE_SET_BREAK		= 0x00000006, // SUSPEND CHARACTER TRANSMISSION FOR A SPECIFIED COMMUNICATIONS DEVICE AND PLACES THE TRANSMISSION LINE IN A BREAK STATE UNTIL THE CLEARCOMMBREAK FUNCTION IS CALLED

	BOSERCN_SERIAL_PORT_SIGNAL_TYPE_CLEAR_BREAK	= 0x00000007, // RESTORE CHARACTER TRANSMISSION FOR A SPECIFIED COMMUNICATIONS DEVICE AND PLACES THE TRANSMISSION LINE IN A NONBREAK STATE
};

// CALLBACK FUNCTION TYPES //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
typedef BRETURN (BOSERCN_EXPORT *PF_BOSERCN_NO_SIGNAL_DETECTED_CALLBACK)( PVOID pDevice /*IN*/, ULONG nVideoInput /*IN*/, ULONG nAudioInput /*IN*/, PVOID pUserData /*IN*/ );

typedef BRETURN (BOSERCN_EXPORT *PF_BOSERCN_SIGNAL_REMOVED_CALLBACK)( PVOID pDevice /*IN*/, ULONG nVideoInput /*IN*/, ULONG nAudioInput /*IN*/, PVOID pUserData /*IN*/ );

typedef BRETURN (BOSERCN_EXPORT *PF_BOSERCN_FORMAT_CHANGED_CALLBACK)( PVOID pDevice /*IN*/, ULONG nVideoInput /*IN*/, ULONG nAudioInput /*IN*/, ULONG nVideoWidth /*IN*/, ULONG nVideoHeight /*IN*/, BOOL bVideoIsInterleaved /*IN*/, double dVideoFrameRate /*IN*/, ULONG nAudioChannels /*IN*/, ULONG nAudioBitsPerSample /*IN*/, ULONG nAudioSampleFrequency /*IN*/, PVOID pUserData /*IN*/ );

typedef BRETURN (BOSERCN_EXPORT *PF_BOSERCN_VIDEO_PREVIEW_CALLBACK)( PVOID pDevice /*IN*/, double dSampleTime /*IN*/, BYTE * pFrameBuffer /*IN*/, ULONG nFrameBufferLen /*IN*/, PVOID pUserData /*IN*/ );

typedef BRETURN (BOSERCN_EXPORT *PF_BOSERCN_AUDIO_PREVIEW_CALLBACK)( PVOID pDevice /*IN*/, double dSampleTime /*IN*/, BYTE * pFrameBuffer /*IN*/, ULONG nFrameBufferLen /*IN*/, PVOID pUserData /*IN*/ );

typedef BRETURN (BOSERCN_EXPORT *PF_BOSERCN_VIDEO_HARDWARE_ENCODER_CALLBACK)( PVOID pDevice /*IN*/, UINT iRecNum /*IN*/, double dSampleTime /*IN*/, BYTE * pStreamBuffer /*IN*/, ULONG nStreamBufferLen /*IN*/, BOOL bIsKeyFrame /*IN*/, PVOID pUserData /*IN*/ );

// CALLBACK FUNCTIONS PART.I (EVENT) ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// 
BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_REGISTER_NO_SIGNAL_DETECTED_CALLBACK( PVOID pDevice /*IN*/, PF_BOSERCN_NO_SIGNAL_DETECTED_CALLBACK pCB /*IN*/, PVOID pUserData /*IN*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_REGISTER_SIGNAL_REMOVED_CALLBACK( PVOID pDevice /*IN*/, PF_BOSERCN_SIGNAL_REMOVED_CALLBACK pCB /*IN*/, PVOID pUserData /*IN*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_REGISTER_FORMAT_CHANGED_CALLBACK( PVOID pDevice /*IN*/, PF_BOSERCN_FORMAT_CHANGED_CALLBACK pCB /*IN*/, PVOID pUserData /*IN*/ );

// CALLBACK FUNCTIONS PART.II (DATA) ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// 
BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_REGISTER_VIDEO_PREVIEW_CALLBACK( PVOID pDevice /*IN*/, PF_BOSERCN_VIDEO_PREVIEW_CALLBACK pCB /*IN*/, PVOID pUserData /*IN*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_REGISTER_AUDIO_PREVIEW_CALLBACK( PVOID pDevice /*IN*/, PF_BOSERCN_AUDIO_PREVIEW_CALLBACK pCB /*IN*/, PVOID pUserData /*IN*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_REGISTER_VIDEO_HARDWARE_ENCODER_CALLBACK( PVOID pDevice /*IN*/, UINT iRecNum /*IN*/, PF_BOSERCN_VIDEO_HARDWARE_ENCODER_CALLBACK pCB /*IN*/, PVOID pUserData /*IN*/ );

// SYSTEM FUNCTIONS /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// 
BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_GET_VERSION( ULONG * pMajorVersion /*OUT*/, ULONG * pMinorVersion /*OUT*/ );

// DEVICE FUNCTIONS /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// 
BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_CREATE( CHAR * pszDevName /*IN*/, UINT iDevNum /*IN*/, HWND hAttachedWindow /*IN*/, PVOID * ppDevice /*OUT*/, BOOL bThumbDraw = FALSE /*IN*/, BOOL bMaintainAspectRatio = FALSE /*IN*/ );

// DEVICE NAME TABLE:
//
// "DC1150 USB" IS FOR PD652, PD652.3D
//
// "QP0204 USB" IS FOR PD5A0
//
// "UB658G USB" IS FOR UB658
//
// "CY3014 USB" IS FOR UB530
//
// "UB3200 USB" IS FOR PD560
//
// "UB3300 USB" IS FOR PD570
//
// "TW6802 PCI" IS FOR SC200, SC300, SC230, SC330
//
// "CX2581 PCI" IS FOR SC310, SC340
//
// "CX2385 PCI" IS FOR SC350
//
// "AH8400 PCI" IS FOR SC290, SC390
//
// "FH8735 PCI" IS FOR SC2A0, SC3A0
//
// "TW5864 PCI" IS FOR SC2B0, SC3B0
//
// "MZ0380 PCI" IS FOR SC3C0
//
// "SA7160 PCI" IS FOR SC500, SC510, TB510
//
// "FH8735 PCI" IS FOR SC580
//
// "TW2809 PCI" IS FOR SC590
//
// "QP0203 PCI" IS FOR SC540, SC5A0
//
// "MZ0380 PCI" IS FOR SC350, SC3C0, SC550, SC560, SC5C0
//
//     "CAMERA" IS FOR GENERAL USB CAMERA
//
//  "SOUNDCARD" IS FOR GENERAL SOUND CARD
//
//    "DESKTOP" IS FOR GENERAL DESKTOP SCREEN GRABBER

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_DESTROY( PVOID pDevice /*IN*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_RUN( PVOID pDevice /*IN*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_STOP( PVOID pDevice /*IN*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_GET_VIDEO_INPUT( PVOID pDevice /*IN*/, ULONG * pInput /*OUT*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_SET_VIDEO_INPUT( PVOID pDevice /*IN*/, ULONG nInput /*IN*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_GET_AUDIO_INPUT( PVOID pDevice /*IN*/, ULONG * pInput /*OUT*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_SET_AUDIO_INPUT( PVOID pDevice /*IN*/, ULONG nInput /*IN*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_GET_VIDEO_STANDARD( PVOID pDevice /*IN*/, ULONG * pStandard /*OUT*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_SET_VIDEO_STANDARD( PVOID pDevice /*IN*/, ULONG nStandard /*IN*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_GET_VIDEO_DEFAULT_OUTPUT_FORMAT( PVOID pDevice /*IN*/, ULONG * pColorSpaceType /*OUT*/, ULONG * pWidth /*OUT*/, ULONG * pHeight /*OUT*/, BOOL * pIsInterleaved /*OUT*/, double * pFrameRate /*OUT*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_SET_VIDEO_DEFAULT_OUTPUT_FORMAT( PVOID pDevice /*IN*/, ULONG nColorSpaceType /*IN*/, ULONG nWidth /*IN*/, ULONG nHeight /*IN*/, BOOL bIsInterleaved /*IN*/, double dFrameRate /*IN*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_GET_AUDIO_DEFAULT_OUTPUT_FORMAT( PVOID pDevice /*IN*/, ULONG * pChannels /*OUT*/, ULONG * pBitsPerSample /*OUT*/, ULONG * pSampleFrequency /*OUT*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_SET_AUDIO_DEFAULT_OUTPUT_FORMAT( PVOID pDevice /*IN*/, ULONG nChannels /*IN*/, ULONG nBitsPerSample /*IN*/, ULONG nSampleFrequency /*IN*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_GET_VIDEO_DEINTERLACE_TYPE( PVOID pDevice /*IN*/, ULONG * pType /*OUT*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_SET_VIDEO_DEINTERLACE_TYPE( PVOID pDevice /*IN*/, ULONG nType /*IN*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_GET_VIDEO_DEINTERLACE( PVOID pDevice /*IN*/, BOOL * pEnable /*OUT*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_SET_VIDEO_DEINTERLACE( PVOID pDevice /*IN*/, BOOL bEnable /*IN*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_GET_VIDEO_HARDWARE_ENCODER_PROPERTY( PVOID pDevice /*IN*/, UINT iRecNum /*IN*/, ULONG * pEncoderFormat /*OUT*/, ULONG * pRecordMode /*OUT*/, ULONG * pQuality /*OUT*/, ULONG * pBitRate /*OUT*/, ULONG * pGOP /*OUT*/, ULONG * pAspectRatioX /*OUT*/, ULONG * pAspectRatioY /*OUT*/, ULONG * pDownscaleMode /*OUT*/, ULONG * pPostSkipFrameRate /*OUT*/ /*DEFAULT = 0*/, ULONG * pPostAvgFrameRate /*OUT*/ /*DEFAULT = 0*/ ); // SKIP = -1 (0xFFFFFFFF)

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_SET_VIDEO_HARDWARE_ENCODER_PROPERTY( PVOID pDevice /*IN*/, UINT iRecNum /*IN*/, ULONG   nEncoderFormat /*IN*/,  ULONG   nRecordMode /*IN*/,  ULONG   nQuality /*IN*/,  ULONG   nBitRate /*IN*/,  ULONG   nGOP /*IN*/,  ULONG   nAspectRatioX /*IN*/,  ULONG   nAspectRatioY /*IN*/,  ULONG   nDownscaleMode /*IN*/,  ULONG   nPostSkipFrameRate /*IN*/  /*DEFAULT = 0*/, ULONG   nPostAvgFrameRate /*IN*/  /*DEFAULT = 0*/ ); // SKIP = -1 (0xFFFFFFFF)

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_GET_AUDIO_SOUND_RENDERER( PVOID pDevice /*IN*/, UINT * pSoundNum /*OUT*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_SET_AUDIO_SOUND_RENDERER( PVOID pDevice /*IN*/, UINT iSoundNum /*IN*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_GET_AUDIO_VOLUME( PVOID pDevice /*IN*/, ULONG * pVolume /*OUT*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_SET_AUDIO_VOLUME( PVOID pDevice /*IN*/, ULONG nVolume /*IN*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_GET_DEVICE_CUSTOM_PROPERTY( PVOID pDevice /*IN*/, ULONG nProperty /*IN*/, ULONG * pValue /*OUT*/ ); // = AMESDK_GET_CUSTOM_PROPERTY. PLS CHECK PRODUCT'S EXTRA PROGRAMMING GUIDE.

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_SET_DEVICE_CUSTOM_PROPERTY( PVOID pDevice /*IN*/, ULONG nProperty /*IN*/, ULONG nValue /*IN*/ ); // = AMESDK_SET_CUSTOM_PROPERTY. PLS CHECK PRODUCT'S EXTRA PROGRAMMING GUIDE.

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_GET_DEVICE_CUSTOM_PROPERTY_EX( PVOID pDevice /*IN*/, ULONG nProperty /*IN*/, BYTE * pValue /*OUT*/, ULONG nBytes /*IN*/ ); // = AMESDK_GET_CUSTOM_PROPERTY_EX. PLS CHECK PRODUCT'S EXTRA PROGRAMMING GUIDE.

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_GET_AUDIO_SOUND_RENDERER( PVOID pDevice /*IN*/, UINT * pSoundNum /*OUT*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_SET_AUDIO_SOUND_RENDERER( PVOID pDevice /*IN*/, UINT iSoundNum /*IN*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_GET_AUDIO_VOLUME( PVOID pDevice /*IN*/, ULONG * pVolume /*OUT*/ );

BOSERCN_EXT_API BRESULT BOSERCN_EXPORT BOSERCN_SET_AUDIO_VOLUME( PVOID pDevice /*IN*/, ULONG nVolume /*IN*/ );

#ifdef __cplusplus
}
#endif

#undef DEFVAL

#endif // BOSERCN_H