#ifndef __QCAP_EXT_CORE_H__
#define __QCAP_EXT_CORE_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

enum {
	QCAP_RS_ERROR_END_OF_FILE = 0x81000000,
};

// RECORD FLAG EXTEND
//
enum {
	QCAP_RECORD_FLAG_PASS_THROUGH					= 0x80000000,
	QCAP_RECORD_FLAG_MODIFY_ONLY					= 0x40000000,
	QCAP_RECORD_FLAG_ROTATE_FIT						= 0x20000000,
	QCAP_RECORD_FLAG_ROTATE_STRETCH					= 0x10000000,
};

// COLOR SPACE TYPE
enum {
	QCAP_COLORSPACE_TYPE_BGRP = 0x50524742,
	QCAP_COLORSPACE_TYPE_GBRP = 0x50524247,
	// QCAP_COLORSPACE_TYPE_YV21 = QCAP_COLORSPACE_TYPE_I420,
	QCAP_COLORSPACE_TYPE_RGBP_FLOAT = 0x50464752,
	QCAP_COLORSPACE_TYPE_Y444 = 0x34343459,
	QCAP_COLORSPACE_TYPE_YUVA420P = 0x32314159,
	QCAP_COLORSPACE_TYPE_NV16 = 0x3631564E,
	QCAP_COLORSPACE_TYPE_NV24 = 0x3432564E,
	QCAP_COLORSPACE_TYPE_Y8 = 0x20203859,
	QCAP_COLORSPACE_TYPE_Y210 = 0x30313259,
	QCAP_COLORSPACE_TYPE_YV16 = 0x36315659,
	QCAP_COLORSPACE_TYPE_I422 = 0x32323449,

	QCAP_COLORSPACE_TYPE_RGB444LE = 0xFF000001,
	QCAP_COLORSPACE_TYPE_RGB444BE = 0xFF000002,
	QCAP_COLORSPACE_TYPE_BGR444LE = 0xFF000003,
	QCAP_COLORSPACE_TYPE_BGR444BE = 0xFF000004,

	QCAP_COLORSPACE_TYPE_UNDEFINED = 0xFFFFFFFF,
};

// INPUT VIDEO SOURCE
//
enum {
	QCAP_INPUT_TYPE_TVI = 100,
	QCAP_INPUT_TYPE_SENSOR,
	QCAP_INPUT_TYPE_UNDEFINED = 0xFFFFFFFF,
	QCAP_INPUT_TYPE_DISPLAY_PORT_MST = 0x80000002,
	QCAP_INPUT_TYPE_DISPLAY_PORT_SST = 0x80000102,
};

// INPUT AUDIO SOURCE
//
enum {
	QCAP_INPUT_TYPE_MICROPHONE = 1002,
	QCAP_INPUT_TYPE_AUDIO_MIXER,
};

// ENCODER TYPE (RECORD PROPERTY)
//
enum {
	QCAP_ENCODER_TYPE_ZZNVCODEC = 1005,
	QCAP_ENCODER_TYPE_GST_SOFTWARE,
	QCAP_ENCODER_TYPE_GST_VAAPI,
	QCAP_ENCODER_TYPE_GST_NVENC,
	QCAP_ENCODER_TYPE_GST_XLNK,
	QCAP_ENCODER_TYPE_CCIMS,
	QCAP_ENCODER_TYPE_NDICODEC,
	QCAP_ENCODER_TYPE_HIMPP,
	QCAP_ENCODER_TYPE_RKMPP,
	QCAP_ENCODER_TYPE_ALLEGRO,
	QCAP_ENCODER_TYPE_VAAPI,
	QCAP_ENCODER_TYPE_EXTERNAL,
	QCAP_ENCODER_TYPE_V4L2SRC,
	QCAP_ENCODER_TYPE_V4L2NVCODEC,
	QCAP_ENCODER_TYPE_NVT_HDAL,
	QCAP_ENCODER_TYPE_ZZNVCODEC2, // built from qcap2
	QCAP_ENCODER_TYPE_ALLEGRO2, // v2023.2
	QCAP_ENCODER_TYPE_UNDEFINED = 0xFFFFFFFF,
};

// DECODER TYPE (PLAYBACK PROPERTY)
//
enum {
	QCAP_DECODER_TYPE_ZZNVCODEC		= 1005,
	QCAP_DECODER_TYPE_GST_SOFTWARE,
	QCAP_DECODER_TYPE_GST_VAAPI,
	QCAP_DECODER_TYPE_GST_NVDEC,
	QCAP_DECODER_TYPE_GST_XLNK,
	QCAP_DECODER_TYPE_CCIMS,
	QCAP_DECODER_TYPE_NDICODEC,
	QCAP_DECODER_TYPE_HIMPP,
	QCAP_DECODER_TYPE_RKMPP,
	QCAP_DECODER_TYPE_ALLEGRO,
	QCAP_DECODER_TYPE_UNDEFINED = 0xFFFFFFFF,
};

// AUDIO SAMPLE FORMAT
//
enum {
	QCAP_SAMPLE_FMT_NONE		= -1,
	QCAP_SAMPLE_FMT_U8			= 0,
	QCAP_SAMPLE_FMT_S16,
	QCAP_SAMPLE_FMT_S32,
	QCAP_SAMPLE_FMT_FLT,
	QCAP_SAMPLE_FMT_DBL,
	QCAP_SAMPLE_FMT_U8P,
	QCAP_SAMPLE_FMT_S16P,
	QCAP_SAMPLE_FMT_S32P,
	QCAP_SAMPLE_FMT_FLTP,
	QCAP_SAMPLE_FMT_DBLP,
};

// CODEC FORMAT (RECORD PROPERTY)
//
enum {
	QCAP_ENCODER_FORMAT_PCM_LE		= QCAP_ENCODER_FORMAT_PCM,
	QCAP_ENCODER_FORMAT_MJPEG		= 1000,
	QCAP_ENCODER_FORMAT_JPEG,
	QCAP_ENCODER_FORMAT_PCM_BE,
	QCAP_ENCODER_FORMAT_S302M,
	QCAP_ENCODER_FORMAT_SHQ0,
	QCAP_ENCODER_FORMAT_SHQ2,
	QCAP_ENCODER_FORMAT_PCM_FLT,
	QCAP_ENCODER_FORMAT_UNDEFINED	= 0xFFFFFFFF,

	QCAP_DECODER_FORMAT_AAC 		= QCAP_ENCODER_FORMAT_AAC,
	QCAP_DECODER_FORMAT_AAC_ADTS	= QCAP_ENCODER_FORMAT_AAC_ADTS,
	QCAP_DECODER_FORMAT_PCM			= QCAP_ENCODER_FORMAT_PCM,
	QCAP_DECODER_FORMAT_PCM_LE		= QCAP_ENCODER_FORMAT_PCM_LE,
	QCAP_DECODER_FORMAT_MJPEG		= QCAP_ENCODER_FORMAT_MJPEG,
	QCAP_DECODER_FORMAT_JPEG		= QCAP_ENCODER_FORMAT_JPEG,
	QCAP_DECODER_FORMAT_PCM_BE		= QCAP_ENCODER_FORMAT_PCM_BE,
	QCAP_DECODER_FORMAT_S302M		= QCAP_ENCODER_FORMAT_S302M,
	QCAP_DECODER_FORMAT_SHQ0		= QCAP_ENCODER_FORMAT_SHQ0,
	QCAP_DECODER_FORMAT_SHQ2		= QCAP_ENCODER_FORMAT_SHQ2,
	QCAP_DECODER_FORMAT_PCM_FLT		= QCAP_ENCODER_FORMAT_PCM_FLT,
	QCAP_DECODER_FORMAT_UNDEFINED	= 0xFFFFFFFF,
};

// RECORD MODE (RECORD PROPERTY)
//
enum {
	QCAP_RECORD_MODE_FIXQP	= 0x1000,
};

// constant
enum {
	QCAP_HWND_DRM_PLANE_ID_MASK = 0xFFFF0000,
};

// global custom property

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif // __QCAP_EXT_CORE_H__
