#ifndef MOCK_QCAP_COMMON_H
#define MOCK_QCAP_COMMON_H

#include "qcap_mock_common.h"
#include "mock_qcap_osd.h"
#include "mock_qcap_linux.h"
#include "mock_qcap_burning.h"
#include "mock_qcap_timer.h"
#include "mock_qcap_helper.h"
#include "mock_qcap_device.h"
#include "mock_qcap_onvif.h"
#include "mock_qcap_recording.h"
#include "mock_qcap_h2.h"
#include "mock_qcap_hl7.h"
#include "mock_qcap_ccvt.h"
#include "mock_qcap_types.h"
#include "mock_qcap_broadcast.h"
#include "mock_qcap_dicom.h"
#include "mock_qcap_h.h"
#include "mock_qcap_windef.h"
#include "mock_qcap_hi3531a.h"
#include "mock_qcap_animation.h"
#include "mock_qcap_webrtc.h"
#include "mock_qcap_sip.h"
#include "mock_qcap_callbacks.h"
#include "mock_qcap_system.h"
#include "mock_qcap_serial.h"
#include "mock_qcap_virtualcamera.h"
#include "mock_qcap_playback.h"

#ifdef __cplusplus
extern "C"
{
#endif

// Typedefs
typedef QRETURN (QCAP_EXPORT *PF_AUDIO_FILE_CALLBACK)( PVOID pFile, double dSampleTime, BYTE * pStreamBuffer, ULONG nStreamBufferLen, PVOID pUserData);
typedef QRETURN (QCAP_EXPORT *PF_BACKCHANNEL_BROADCAST_SERVER_AUDIO_DECODED_CALLBACK)( PVOID pServer, UINT iSessionNum, double dSampleTime, BYTE * pFrameBuffer, ULONG nFrameBufferLen, PVOID pUserData );
typedef QRETURN (QCAP_EXPORT *PF_BACKCHANNEL_BROADCAST_SERVER_PLAY_CALLBACK)( PVOID pServer, UINT iSessionNum, PVOID pUserData );
typedef QRETURN (QCAP_EXPORT *PF_BACKCHANNEL_BROADCAST_SERVER_STOP_CALLBACK)( PVOID pServer, UINT iSessionNum, PVOID pUserData );
typedef QRETURN (QCAP_EXPORT *PF_CLIENT_CONNECTED_BROADCAST_SERVER_CALLBACK)( PVOID pServer, UINT iSessionNum, PVOID pConnectionInfos, PVOID pUserData );
typedef QRETURN (QCAP_EXPORT *PF_CLIENT_DISCONNECTED_BROADCAST_SERVER_CALLBACK)( PVOID pServer, UINT iSessionNum, PVOID pConnectionInfos, PVOID pUserData );
typedef QRETURN (QCAP_EXPORT *PF_DANTE_SERVER_NO_RESPOND_CALLBACK)( PVOID pServer /*IN*/, BOOL bActivate, PVOID pUserData /*IN*/ );
typedef QRETURN (QCAP_EXPORT *PF_DANTE_SERVER_TX_AUDIO_REQUEST_CALLBACK)( PVOID pServer /*IN*/, double dSampleTime /*IN*/, PVOID pUserData /*IN*/ );
typedef QRETURN (QCAP_EXPORT *PF_MEDIA_BROADCAST_SERVER_CALLBACK)( PVOID pServer, UINT iSessionNum, double dSampleTime, BYTE * pStreamBuffer, ULONG nStreamBufferLen, PVOID pUserData );
typedef QRETURN (QCAP_EXPORT *PF_NDI_DISCOVERY_SERVICE_CONNECTED_BROADCAST_CLIENT_CALLBACK)( PVOID pClient, UINT iSessionNum, BOOL bServiceConnected, CHAR * pszNDIName, CHAR * pszGroupName, PVOID pUserData );
typedef QRETURN (QCAP_EXPORT *PF_NDI_METADATA_BROADCAST_CLIENT_CALLBACK)( PVOID pClient, UINT iSessionNum, int length, int64_t timecode, const char* p_data, PVOID pUserData );
typedef QRETURN (QCAP_EXPORT *PF_PATGEN_AUDIO_PREVIEW_CALLBACK)(PVOID pPatGen, double dSampleTime, BYTE * pFrameBuffer, ULONG nFrameBufferLen, PVOID pUserData);
typedef QRETURN (QCAP_EXPORT *PF_PATGEN_FORMAT_CHANGED_CALLBACK)(PVOID pPatGen, ULONG nColorSpaceType, ULONG nVideoWidth, ULONG nVideoHeight, BOOL bVideoIsInterleaved, double dVideoFrameRate, ULONG nAudioChannels, ULONG nAudioBitsPerSample, ULONG nAudioSampleFrequency, PVOID pUserData);
typedef QRETURN (QCAP_EXPORT *PF_PATGEN_VIDEO_PREVIEW_CALLBACK)(PVOID pPatGen, double dSampleTime, BYTE * pFrameBuffer, ULONG nFrameBufferLen, PVOID pUserData);
typedef QRETURN (QCAP_EXPORT *PF_SHARE_RECORD_CALLBACK)( UINT iRecNum /*IN*/, BYTE * pStreamBuffer /*IN*/, ULONG nStreamBufferLen /*IN*/, PVOID pUserData /*IN*/ );
typedef QRETURN (QCAP_EXPORT *PF_UDEVMON_BIND_CALLBACK)(PVOID pUdevMonitor, ULONG pDeviceInfos[3], PVOID pUserData);
typedef QRETURN (QCAP_EXPORT *PF_UDEVMON_UNBIND_CALLBACK)(PVOID pUdevMonitor, PVOID pUserData);
typedef QRETURN (QCAP_EXPORT *PF_VIDEO_FILE_CALLBACK)( PVOID pFile, double dSampleTime, BYTE * pStreamBuffer, ULONG nStreamBufferLen, BOOL bIsKeyFrame, PVOID pUserData);

// Function Declarations
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_INITIALIZE();
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_UNINITIALIZE();
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_SET_CUSTOM_PROPERTY(ULONG nProperty, BYTE* pValue, ULONG nBytes);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_GET_CUSTOM_PROPERTY(ULONG nProperty, BYTE* pValue, ULONG nBytes);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_SYNCHRONIZED_SNAPSHOT_BMP(ULONG nFileArgs, CHAR * pszFilePathName1, PVOID pDevice1, CHAR * pszFilePathName2, PVOID pDevice2, ...);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_SYNCHRONIZED_SNAPSHOT_JPG(ULONG nFileArgs, CHAR * pszFilePathName1, ULONG nQuality1, PVOID pDevice1, CHAR * pszFilePathName2, ULONG nQuality2, PVOID pDevice2, ...);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_COLORSPACE_RGB24_TO_YUY2(BYTE * pSrcFrameBuffer, ULONG nSrcWidth, ULONG nSrcHeight, ULONG nSrcPitch, BYTE * pDstFrameBuffer, ULONG nDstWidth, ULONG nDstHeight, ULONG nDstPitch, BOOL bHorizontalMirror, BOOL bVerticalMirror);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_COLORSPACE_RGB24_TO_YV12(BYTE * pSrcFrameBuffer, ULONG nSrcWidth, ULONG nSrcHeight, ULONG nSrcPitch, BYTE * pDstFrameBuffer, ULONG nDstWidth, ULONG nDstHeight, ULONG nDstPitch, BOOL bHorizontalMirror, BOOL bVerticalMirror);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_COLORSPACE_ARGB32_TO_YUY2(BYTE * pSrcFrameBuffer, ULONG nSrcWidth, ULONG nSrcHeight, ULONG nSrcPitch, BYTE * pDstFrameBuffer, ULONG nDstWidth, ULONG nDstHeight, ULONG nDstPitch, BOOL bHorizontalMirror, BOOL bVerticalMirror);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_COLORSPACE_ARGB32_TO_YV12(BYTE * pSrcFrameBuffer, ULONG nSrcWidth, ULONG nSrcHeight, ULONG nSrcPitch, BYTE * pDstFrameBuffer, ULONG nDstWidth, ULONG nDstHeight, ULONG nDstPitch, BOOL bHorizontalMirror, BOOL bVerticalMirror);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_COLORSPACE_YUY2_TO_UYVY(BYTE * pSrcFrameBuffer, ULONG nSrcWidth, ULONG nSrcHeight, ULONG nSrcPitch, BYTE * pDstFrameBuffer, ULONG nDstWidth, ULONG nDstHeight, ULONG nDstPitch, BOOL bHorizontalMirror, BOOL bVerticalMirror);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_COLORSPACE_YV12_TO_UYVY(BYTE * pSrcFrameBuffer, ULONG nSrcWidth, ULONG nSrcHeight, ULONG nSrcPitch, BYTE * pDstFrameBuffer, ULONG nDstWidth, ULONG nDstHeight, ULONG nDstPitch, BOOL bHorizontalMirror, BOOL bVerticalMirror);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_COLORSPACE_NV12_TO_UYVY(BYTE * pSrcFrameBuffer, ULONG nSrcWidth, ULONG nSrcHeight, ULONG nSrcPitch, BYTE * pDstFrameBuffer, ULONG nDstWidth, ULONG nDstHeight, ULONG nDstPitch, BOOL bHorizontalMirror, BOOL bVerticalMirror);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_COLORSPACE_CONVERT(ULONG nSrcColorSpaceType, BYTE * pSrcFrameBuffer, ULONG nSrcWidth, ULONG nSrcHeight, ULONG nSrcPitch, ULONG nDstColorSpaceType, BYTE * pDstFrameBuffer, ULONG nDstWidth, ULONG nDstHeight, ULONG nDstPitch, BOOL bHorizontalMirror, BOOL bVerticalMirror);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CROP_VIDEO_FRAME(BYTE* pSrcFrameBuffer, ULONG nSrcFrameBufferLen, ULONG nCropX, ULONG nCropY, ULONG nCropW, ULONG nCropH, BYTE* pDstFrameBuffer, ULONG nDstFrameBufferLen);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_BUFFER(BYTE** ppBuffer, ULONG* pBufferLen);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_DESTROY_BUFFER(BYTE* pBuffer, ULONG nBufferLen);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_FRAME_BUFFER(BYTE** ppBuffer, ULONG* pBufferLen);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_DESOTRY_FRAME_BUFFER(BYTE * pBuffer, ULONG nBufferLen);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_BLOCK_LOCK(PVOID* ppBlockLock);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_DESTROY_BLOCK_LOCK(PVOID pBlockLock);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_GRANT_BLOCK_LOCK(PVOID pBlockLock, BOOL bGrant);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_ENTER_BLOCK_LOCK(PVOID pBlockLock);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_LEAVE_BLOCK_LOCK(PVOID pBlockLock);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_VIDEO_FRAME_POOL(ULONG nColorSpaceType, ULONG nFrameWidth, ULONG nFrameHeight, ULONG nFrames, PVOID* ppFramePool);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_VIDEO_FRAME_POOL_EX(ULONG nColorSpaceType, ULONG nFrameWidth, ULONG nFrameHeight, ULONG nFrames, BOOL bMapped, PVOID* ppFramePool);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_AUDIO_FRAME_POOL(ULONG nChannels, ULONG nBitsPerSample, ULONG nSampleFrequency, ULONG nFrameSize, ULONG nFrames, PVOID* ppFramePool);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_AUDIO_FRAME_POOL_EX(ULONG nChannels, ULONG nSampleFmt, ULONG nSampleFrequency, ULONG nFrameSize, ULONG nFrames, PVOID* ppFramePool);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_GET_FRAME_BUFFER(PVOID pFramePool, BYTE** ppFrameBuffer, ULONG* pFrameBufferSize);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_DESTROY_FRAME_POOL(PVOID pFramePool);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_AUDIO_RESAMPLER(ULONG nSrcChannels, ULONG nSrcBitsPerSample, ULONG nSrcSampleFrequency, ULONG nDstChannels, ULONG nDstBitsPerSample, ULONG nDstSampleFrequency, PVOID* ppAudioResampler);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_DESTROY_AUDIO_RESAMPLER(PVOID pAudioResampler);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_AUDIO_RESAMPLER_SET_AUDIO_BUFFER(PVOID pAudioResampler, BYTE * pSrcFrameBuffer, ULONG nSrcFrameBufferLen, double dSampleTime);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_AUDIO_RESAMPLER_GET_RESAMPLED_AUDIO_BUFFER(PVOID pAudioResampler, BYTE * pDstFrameBuffer, ULONG nDstFrameBufferLen, double * pSampleTime);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_STREAM_BUFFER_POOL(ULONG nCount, PVOID* ppStreamBufferPool);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_GET_STREAM_BUFFER(PVOID pStreamBufferPool, BYTE** ppStreamBuffer, ULONG* pStreamBufferLen);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_DESTROY_STREAM_BUFFER_POOL(PVOID pStreamBufferPool);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_COPY_NATIVE_STREAM_BUFFER(BYTE* pDstStreamBuffer, ULONG nDstStreamBufferLen, BYTE* pSrcStreamBuffer, ULONG nSrcStreamBufferLen, BOOL bIsKeyFrame, double dSrcSampleTime);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_AUDIO_DELAY_QUEUE(PVOID* ppFrameQueue);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_SET_AUDIO_DELAY(PVOID pFrameQueue, ULONG nMaxDelayInMS);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_PUSH_AUDIO_FRAME_BUFFER(PVOID pFrameQueue, BYTE* pSrcFrameBuffer, ULONG nSrcFrameBufferSize, BYTE** ppDstFrameBuffer, ULONG* pDstFrameBufferSize);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_DESTROY_AUDIO_DELAY_QUEUE(PVOID pFrameQueue);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_STEP_ANIMATION_CLIP2(PVOID pClip, UINT * pFrameNum, BYTE * pFrameBuffer, ULONG nFrameBufferLen);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_GET_ANIMATION_CLIP_BKCOLOR_PROPERTY(PVOID pClip, float* pR, float* pG, float* pB);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_SET_ANIMATION_CLIP_BKCOLOR_PROPERTY(PVOID pClip, float r, float g, float b);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_GET_ANIMATION_CLIP_SPRITE_SCALE_STYLE(PVOID pClip, UINT iSpriteNum, ULONG* pScaleStyle);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_SET_ANIMATION_CLIP_SPRITE_SCALE_STYLE(PVOID pClip, UINT iSpriteNum, ULONG nScaleStyle);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_GET_ANIMATION_CLIP_SPRITE_BKCOLOR(PVOID pClip, UINT iSpriteNum, float* pR, float* pG, float* pB);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_SET_ANIMATION_CLIP_SPRITE_BKCOLOR(PVOID pClip, UINT iSpriteNum, float r, float g, float b);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_GET_ANIMATION_CLIP_SPRITE_STATIC(PVOID pClip, UINT iSpriteNum, BOOL* pStatic);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_SET_ANIMATION_CLIP_SPRITE_STATIC(PVOID pClip, UINT iSpriteNum, BOOL bStatic);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_BROADCAST_TS_OVER_UDP_SERVER_EX(UINT iSvrNum /*0 ~ 63*/, CHAR * pszURL, PVOID * ppServer, CHAR * pszNetworkAdapterIP DEFVAL( NULL), ULONG nServiceID DEFVAL( 1), CHAR * pszServiceName DEFVAL( NULL), CHAR * pszServiceProviderName DEFVAL( NULL), BOOL bEnableCBRMode DEFVAL( TRUE), ULONG nTransferBitRate DEFVAL( 0 /*0 = FREE*/), ULONG nOriginalNetworkID DEFVAL( 1), ULONG nTransportStreamID DEFVAL( 1), ULONG nPMT_PID DEFVAL( 4096), ULONG nPCR_PID DEFVAL( 4097), ULONG nVideo_PID DEFVAL( 256), ULONG nAudio_PID DEFVAL( 257), ULONG nVideo_CodecID DEFVAL( 0 /*0 = AUTO*/), ULONG nAudio_CodecID DEFVAL( 0 /*0 = AUTO*/), ULONG nPCRInterval DEFVAL( 0 /*ms*/ ), ULONG nTTL DEFVAL( 7 ));
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_BROADCAST_TS_OVER_SRT_SERVER_EX(UINT iSvrNum /*0 ~ 63*/, PVOID * ppServer, ULONG nNetworkPort_SRT DEFVAL( 1234 ), CHAR * pszPassPhrase DEFVAL( NULL ), ULONG nPBKeyLen DEFVAL( 16 ),  CHAR * pszNetworkAdapterIP DEFVAL(  NULL ), ULONG nServiceID DEFVAL(1) , CHAR * pszServiceName DEFVAL( NULL ), CHAR * pszServiceProviderName DEFVAL( NULL ) , ULONG nTransferBitRate DEFVAL(0) , ULONG nOriginalNetworkID DEFVAL(1) , ULONG nTransportStreamID DEFVAL( 1), ULONG nPMT_PID DEFVAL( 4096 ), ULONG nPCR_PID DEFVAL( 4097 ), ULONG nVideo_PID DEFVAL(256), ULONG nAudio_PID DEFVAL(257), ULONG nVideo_CodecID DEFVAL(0) /*0 = AUTO*/, ULONG nAudio_CodecID DEFVAL(0) /*0 = AUTO*/, ULONG nPCRInterval DEFVAL(0) /*ms*/, ULONG nSRTLatency DEFVAL(120 ) /*ms*/, ULONG nSRTBandwidth DEFVAL(25 /*100%*/));
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_BROADCAST_TS_OVER_SRT_WEB_PORTAL_SERVER_EX(UINT iSvrNum /*0 ~ 63*/, CHAR * pszURL, PVOID * ppServer, CHAR * pszPassPhrase DEFVAL( NULL ),  ULONG nPBKeyLen DEFVAL( 16 ), ULONG nServiceID DEFVAL( 1 ), CHAR * pszServiceName DEFVAL(NULL), CHAR * pszServiceProviderName DEFVAL(NULL), ULONG nTransferBitRate DEFVAL(0) /*0 DEFVAL(FREE*/, ULONG nOriginalNetworkID DEFVAL(1), ULONG nTransportStreamID DEFVAL(1), ULONG nPMT_PID DEFVAL(4096), ULONG nPCR_PID DEFVAL(4097), ULONG nVideo_PID DEFVAL(256), ULONG nAudio_PID DEFVAL(257), ULONG nVideo_CodecID DEFVAL(0) /*0 = AUTO*/, ULONG nAudio_CodecID DEFVAL( 0 ) /*0 = AUTO*/, ULONG nPCRInterval DEFVAL( 0 ) /*ms*/, ULONG nSRTLatency DEFVAL( 120) /*ms*/, ULONG nSRTOverheadBandwidth DEFVAL( 25 ) /*100%*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_BROADCAST_RTP_SERVER(UINT iSvrNum /*0 ~ 63*/, CHAR* pszIPorSDP, PVOID * ppServer, ULONG nNetworkPort DEFVAL( (ULONG)-1 ));
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_BROADCAST_QCAP_SERVER(UINT iSvrNum /*0 ~ 63*/, ULONG nNetworkPort, PVOID * ppServer);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_REGISTER_MEDIA_BROADCAST_SERVER_CALLBACK(PVOID pServer, UINT iSessionNum, PF_MEDIA_BROADCAST_SERVER_CALLBACK pCB, PVOID pUserData);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_REGISTER_CLIENT_CONNECTED_BROADCAST_SERVER_CALLBACK(PVOID pServer, UINT iSessionNum, PF_CLIENT_CONNECTED_BROADCAST_SERVER_CALLBACK pCB, PVOID pUserData);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_REGISTER_CLIENT_DISCONNECTED_BROADCAST_SERVER_CALLBACK(PVOID pServer, UINT iSessionNum, PF_CLIENT_DISCONNECTED_BROADCAST_SERVER_CALLBACK pCB, PVOID pUserData);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_GET_BROADCAST_SERVER_INFO(PVOID pServer, UINT iSessionNum, ULONG * pConnections);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_SET_BROADCAST_SERVER_CUSTOM_PROPERTY(PVOID pServer, ULONG nProperty, BYTE* pValue, ULONG nBytes);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_GET_BROADCAST_SERVER_CUSTOM_PROPERTY(PVOID pServer, ULONG nProperty, BYTE* pValue, ULONG* pBytes);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_SET_SESSION_BROADCAST_SERVER_CUSTOM_PROPERTY(PVOID pServer, UINT iSessionNum, ULONG nProperty, BYTE* pValue, ULONG nBytes);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_GET_SESSION_BROADCAST_SERVER_CUSTOM_PROPERTY(PVOID pServer, UINT iSessionNum, ULONG nProperty, BYTE* pValue, ULONG* pBytes);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_SET_ID3_BROADCAST_SERVER_COMPRESSION_BUFFER(PVOID pServer, UINT iSessionNum, BYTE * pStreamBuffer, ULONG nStreamBufferLen, double dSampleTime DEFVAL(0.0));
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_BROADCAST_SRT_CLIENT_EX(UINT iCliNum /*0 ~ 63*/, CHAR * pszURL, PVOID * ppClient, ULONG nSRTLatency DEFVAL(120) , ULONG nSRTOverheadBandwidth DEFVAL(25), ULONG nDecoderType DEFVAL( QCAP_DECODER_TYPE_SOFTWARE) , HWND hAttachedWindow DEFVAL(NULL), BOOL bThumbDraw DEFVAL(FALSE), BOOL bMaintainAspectRatio DEFVAL(FALSE), CHAR * pszPassPhrase DEFVAL(NULL),  ULONG nPBKeyLen DEFVAL(16));
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_SET_BROADCAST_CLIENT_CUSTOM_PROPERTY_EX(PVOID pClient, ULONG nProperty, BYTE* pValue, ULONG nBytes);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_GET_BROADCAST_CLIENT_CUSTOM_PROPERTY_EX(PVOID pClient, ULONG nProperty, BYTE* pValue, ULONG* pBytes);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_BROADCAST_NDI_CLIENT_ENUMERATION1(CHAR * * ppszNDIName /*OUT*/, CHAR * * ppszGroupName /*OUT*/, BOOL bShowLocalSource DEFVAL(TRUE) /*IN*/, CHAR* pszGroups DEFVAL(NULL)/*IN*/, CHAR* pszExtraIp DEFVAL(NULL)/*IN*/, BOOL bNext DEFVAL( FALSE /*IN*/ ));
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_REGISTER_NDI_METADATA_BROADCAST_CLIENT_CALLBACK(PVOID pClient /*IN*/, PF_NDI_METADATA_BROADCAST_CLIENT_CALLBACK pCB /*IN*/, PVOID pUserData /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_BROADCAST_NDI_CLIENT1(UINT iCliNum /*IN*/ /*0 ~ 63*/, CHAR * pszDiscoveryServiceIp /*IN*/, PVOID * ppClient /*OUT*/, BOOL bEnableNDIProxy DEFVAL( FALSE /*IN*/), ULONG nDecoderType DEFVAL( QCAP_DECODER_TYPE_SOFTWARE /*IN*/), HWND hAttachedWindow DEFVAL( NULL /*IN*/), BOOL bThumbDraw DEFVAL( FALSE /*IN*/), BOOL bMaintainAspectRatio DEFVAL( FALSE /*IN*/ ));
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_REGISTER_NDI_DISCOVERY_SERVICE_CONNECTED_BROADCAST_CLIENT_CALLBACK(PVOID pClient /*IN*/, PF_NDI_DISCOVERY_SERVICE_CONNECTED_BROADCAST_CLIENT_CALLBACK pCB /*IN*/, PVOID pUserData /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_SET_VIDEO_SHARE_RECORD_CUSTOM_PROPERTY(UINT iRecNum, ULONG nProperty, BYTE* pValue, ULONG nBytes);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_GET_VIDEO_SHARE_RECORD_CUSTOM_PROPERTY(UINT iRecNum, ULONG nProperty, BYTE* pValue, ULONG* pBytes);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_SET_AUDIO_MX_SHARE_RECORD_VOLUME(UINT iRecNum, ULONG nTracks, UINT iMixNum, ULONG  nVolume);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_GET_AUDIO_MX_SHARE_RECORD_VOLUME(UINT iRecNum, ULONG nTracks, UINT iMixNum, ULONG* pVolume);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_REGISTER_SHARE_RECORD_CALLBACK(UINT iRecNum /*IN*/, PF_SHARE_RECORD_CALLBACK pCB /*IN*/, PVOID pUserData /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_GET_FILE_CUSTOM_PROPERTY_EX(PVOID pFile, ULONG nProperty, BYTE * pValue, ULONG* pBytes);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_SET_FILE_CUSTOM_PROPERTY_EX(PVOID pFile, ULONG nProperty, BYTE * pValue, ULONG nBytes);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_REGISTER_VIDEO_FILE_CALLBACK(PVOID pFile, PF_VIDEO_FILE_CALLBACK pCB, PVOID pUserData);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_REGISTER_AUDIO_FILE_CALLBACK(PVOID pFile, PF_AUDIO_FILE_CALLBACK pCB, PVOID pUserData);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_RINGBUFFER(ULONG nMaxSize, PVOID* ppRingBuffer);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_DESTROY_RINGBUFFER(PVOID pRingbuffer);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_ENQUEUE_RINGBUFFER(PVOID pRingbuffer, BYTE* pFrameBuffer, ULONG nFrameBufferLen);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_GET_RINGBUFFER_FRAME_BUFFER(PVOID pRingbuffer, INT nOffset, BYTE** ppFrameBuffer, ULONG* pFrameBufferLen);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_RESET_RINGBUFFER(PVOID pRingbuffer);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_COMPOSITOR(PVOID* ppCompositor);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_DESTROY_COMPOSITOR(PVOID pCompositor);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_BEGIN_COMPOSITE(PVOID pCompositor, BYTE* pFrameBuffer, ULONG nFrameBufferLen);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_COMPOSITE_VIDEO_FRAME(PVOID pCompositor, BYTE* pSrcFrameBuffer, ULONG nSrcFrameBufferLen,
	ULONG nSrcCropX, ULONG nSrcCropY, ULONG nSrcCropW, ULONG nSrcCropH,
	ULONG nDstCropX, ULONG nDstCropY, ULONG nDstCropW, ULONG nDstCropH);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_BLENDOVER_VIDEO_FRAME(PVOID pCompositor, BYTE* pSrcFrameBuffer, ULONG nSrcFrameBufferLen,
	ULONG nSrcCropX, ULONG nSrcCropY, ULONG nSrcCropW, ULONG nSrcCropH,
	ULONG nDstCropX, ULONG nDstCropY, ULONG nDstCropW, ULONG nDstCropH);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_END_COMPOSITE(PVOID pCompositor);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_DANTE_SERVER(PVOID * ppServer /*OUT*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_START_DANTE_SERVER(PVOID pServer /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_STOP_DANTE_SERVER(PVOID pServer /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_DESTROY_DANTE_SERVER(PVOID pServer /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_SEND_DANTE_SERVER_MESSAGE(PVOID pServer, ULONG nVideoTxChannel, ULONG nVideoRxChannel, ULONG nMessage);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_DANTE_SENDER(PVOID pServer /*IN*/, UINT iSvrNum /*IN*/ /*0 ~ 63*/, PVOID * ppSender /*OUT*/, UINT nVideoChannel /*IN*/, UINT nAudioChannel /*IN*/, CHAR * pszNetworkAdapterIP DEFVAL( NULL /*IN*/));
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_DANTE_RECEIVER(PVOID pServer /*IN*/, UINT nVideoChannel /*IN*/, UINT nAudioChannel /*IN*/, UINT iCliNum /*IN*/ /*0 ~ 63*/, PVOID * ppClient /*OUT*/, ULONG nDecoderType DEFVAL( QCAP_DECODER_TYPE_SOFTWARE /*IN*/), HWND hAttachedWindow DEFVAL( NULL /*IN*/), BOOL bThumbDraw DEFVAL( FALSE /*IN*/), BOOL bMaintainAspectRatio DEFVAL( FALSE /*IN*/ ));
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_SET_DANTE_SERVER_CUSTOM_PROPERTY(PVOID pServer /*IN*/, ULONG nTotalVideoSenderChannels, ULONG nTotalVideoReceiverChannels);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_GET_DANTE_SERVER_CUSTOM_PROPERTY(PVOID pServer /*IN*/, ULONG* nTotalVideoSenderChannels /*OUT*/, ULONG* nTotalVideoReceiverChannels /*OUT*/, ULONG* nTotalAudioSenderChannels /*OUT*/, ULONG* nTotalAudioReceiverChannels /*OUT*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_REGISTER_DANTE_SERVER_MESSAGE_CALLBACK(PVOID pServer /*IN*/, PF_DANTE_SERVER_MESSAGE_CALLBACK pCB /*IN*/, PVOID pUserData /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_REGISTER_DANTE_SERVER_TX_AUDIO_REQUEST_CALLBACK(PVOID pServer /*IN*/, PF_DANTE_SERVER_TX_AUDIO_REQUEST_CALLBACK pCB /*IN*/, PVOID pUserData /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_REGISTER_DANTE_SERVER_NO_RESPOND_CALLBACK(PVOID pServer /*IN*/, PF_DANTE_SERVER_NO_RESPOND_CALLBACK pCB /*IN*/, PVOID pUserData /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_REGISTER_DANTE_SERVER_MESSAGE_CALLBACK1(PVOID pServer /*IN*/, PF_DANTE_SERVER_MESSAGE_CALLBACK1 pCB /*IN*/, PVOID pUserData /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_BROADCAST_NDI_SERVER2(UINT iSvrNum, ULONG nTotalSessions, PVOID * ppServer, CHAR * pszNDIName, CHAR * pszGroupName, BOOL bEnablePTZ, CHAR * pszConnectionMetadata);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_PATGEN(PVOID* ppPatGen);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_DESTROY_PATGEN(PVOID pPatGen);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_RUN_PATGEN(PVOID pPatGen);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_STOP_PATGEN(PVOID pPatGen);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_SET_PATGEN_VIDEO_OUTPUT_FORMAT(PVOID pPatGen, ULONG nColorSpaceType, ULONG nWidth, ULONG nHeight, BOOL bIsInterleaved, double dFrameRate);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_SET_PATGEN_AUDIO_OUTPUT_FORMAT(PVOID pPatGen, ULONG nChannels, ULONG nBitsPerSample, ULONG nSampleFrequency);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_SET_PATGEN_CUSTOM_PROPERTY(PVOID pPatGen, ULONG nProperty, BYTE* pValue, ULONG nBytes);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_GET_PATGEN_CUSTOM_PROPERTY(PVOID pPatGen, ULONG nProperty, BYTE* pValue, ULONG nBytes);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_REGISTER_PATGEN_FORMAT_CHANGED_CALLBACK(PVOID pPatGen, PF_PATGEN_FORMAT_CHANGED_CALLBACK pCB, PVOID pUserData);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_REGISTER_PATGEN_VIDEO_PREVIEW_CALLBACK(PVOID pPatGen, PF_PATGEN_VIDEO_PREVIEW_CALLBACK pCB, PVOID pUserData);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_REGISTER_PATGEN_AUDIO_PREVIEW_CALLBACK(PVOID pPatGen, PF_PATGEN_AUDIO_PREVIEW_CALLBACK pCB, PVOID pUserData);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_UDEVMON(PVOID* ppUdevMonitor);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_DESTROY_UDEVMON(PVOID pUdevMonitor);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_RUN_UDEVMON(PVOID pUdevMonitor);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_STOP_UDEVMON(PVOID pUdevMonitor);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_REGISTER_UDEVMON_BIND_CALLBACK(PVOID pUdevMonitor, PF_UDEVMON_BIND_CALLBACK pCB, PVOID pUserData);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_REGISTER_UDEVMON_UNBIND_CALLBACK(PVOID pUdevMonitor, PF_UDEVMON_UNBIND_CALLBACK pCB, PVOID pUserData);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_GET_COMMUNICATION_SERVER_AUDIO_DECODER(PVOID pServer, UINT iAudDecNum, ULONG * pDecoderFormat, ULONG * pChannels, ULONG * pBitsPerSample, ULONG * pSampleFrequency, ULONG * pBitRate_Min, ULONG * pBitRate_Max, ULONG * pBitRate_Default);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_SET_COMMUNICATION_SERVER_AUDIO_DECODER(PVOID pServer, UINT iAudEncNum, ULONG nEncoderFormat, ULONG nChannels, ULONG nBitsPerSample, ULONG nSampleFrequency, ULONG nBitRate_Min, ULONG nBitRate_Max, ULONG nBitRate_Default);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_GET_COMMUNICATION_EMULATOR_SERVER_INFO_EX(PVOID pEmulator, UINT iSvrNum, CHAR * * ppszNetworkIP, ULONG * pNetworkPort, CHAR * * ppszNetworkURL, CHAR * * ppszName, CHAR * * ppszLocation);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CAMERA_ENUMERATION2(CHAR * * ppszCameraDevName /*OUT*/, BOOL bNext /*IN*/, ULONG pEncoderFormat /*IN*/, BOOL * bIncluded /*OUT*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_ALLOC_VIDEO_GPUDIRECT_PREVIEW_BUFFER_EX(PVOID pDevice /*IN*/, BYTE * * ppFrameBuffer /*OUT*/, ULONG nFrameBufferLen /*IN*/, ULONG nAllocMode = QCAP_CUDAHOST_ALLOC_MAPPED);

#ifdef __cplusplus
}
#endif

#endif // MOCK_QCAP_COMMON_H
