#ifndef MOCK_QCAP_TIMER_H
#define MOCK_QCAP_TIMER_H

#include "qcap_mock_common.h"

#ifdef __cplusplus
extern "C"
{
#endif

// Function Declarations
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_MEDIA_TIMER(ULONG nElapseTimeNum /*IN*/, ULONG nElapseTimeDeno /*IN*/, PVOID * ppTimer /*OUT*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_DESTROY_MEDIA_TIMER(PVOID pTimer /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_START_MEDIA_TIMER(PVOID pTimer /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_STOP_MEDIA_TIMER(PVOID pTimer /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_REGISTER_MEDIA_TIMER_CALLBACK(PVOID pTimer /*IN*/, PF_MEDIA_TIMER_CALLBACK pCB /*IN*/, PVOID pUserData /*IN*/);

#ifdef __cplusplus
}
#endif

#endif // MOCK_QCAP_TIMER_H
