#ifndef MOCK_QCAP_HI3531A_H
#define MOCK_QCAP_HI3531A_H

#include "qcap_mock_common.h"

#ifdef __cplusplus
extern "C"
{
#endif

// Function Declarations
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_INITIALIZE() __attribute__ ((deprecated));
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_UNINITIALIZE() __attribute__ ((deprecated));
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_SET_CUSTOM_PROPERTY(ULONG nProperty, BYTE* pValue, ULONG nBytes);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_GET_CUSTOM_PROPERTY(ULONG nProperty, BYTE* pValue, ULONG nBytes);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_CREATE_WINDOW(int x, int y, int w, int h, HWND hParent, HWND* pWnd);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_DESTROY_WINDOW(HWND hWnd);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_SHOW_WINDOW(HWND hWnd);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_HIDE_WINDOW(HWND hWnd);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_MOVE_WINDOW(HWND hWnd, int x, int y, int w, int h);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_GET_WINDOW_RECT(HWND hWnd, int* px, int* py, int* pw, int* ph);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_WINDOW_BRING_TO_FRONT(HWND hWnd);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_WINDOW_SEND_TO_BACK(HWND hWnd);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_WINDOW_BRING_FORWARD(HWND hWnd);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_WINDOW_SEND_BACKWARD(HWND hWnd);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_SET_WINDOW_ASPECT_RATIO(HWND hWnd, int flags, int bgColor);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_ENABLE_WINDOW_SPLIT_MODE(HWND hWnd, BOOL bEnable);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_SET_VIDEO_WINDOW_UNCOMPRESSION_BUFFER(HWND hWnd, BYTE * pFrameBuffer /*IN*/, ULONG nFrameBufferLen /*IN*/, double dSampleTime);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_SET_VIDEO_WINDOW_FRAME(HWND hWnd, qcap_generic_av_frame_t* pAVFrame);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_GET_WINDOW_PROPERTY(HWND hWnd, ULONG nProperty, BYTE * pValue /*OUT*/, ULONG nBytes /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_SET_WINDOW_PROPERTY(HWND hWnd, ULONG nProperty, BYTE * pValue /*OUT*/, ULONG nBytes /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_RESET_BROADCAST_SERVER(PVOID pServer, UINT iSessionNum);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_RESET_SHARE_RECORD(UINT iRecodNum);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_BUFFER_ADD_REF(BYTE * pBuffer, ULONG nBufferLen ) __attribute__ ((deprecated));
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_BUFFER_RELEASE(BYTE * pBuffer, ULONG nBufferLen ) __attribute__ ((deprecated));
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_ALPHA_BLEND(ULONG nSrcColorSpaceType /*IN*/, ULONG nSrcWidth /*IN*/, ULONG nSrcHeight /*IN*/, BYTE * pSrcFrameBuffer, ULONG nSrcFrameBufferLen, ULONG nDstColorSpaceType /*IN*/, ULONG nDstWidth /*IN*/, ULONG nDstHeight /*IN*/, BYTE * pDstFrameBuffer, ULONG nDstFrameBufferLen, BYTE bAlpha);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_CLONE_VIDEO_FRAME(ULONG nColorSpaceType /*IN*/, BYTE * pFrameBuffer /*IN*/, ULONG nFrameWidth /*IN*/, ULONG nFrameHeight /*IN*/, ULONG nFramePitch /*IN*/, BYTE ** ppDstFrameBuffer, ULONG* pDstFrameBufferLen);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_CREATE_FRAME_POOL(ULONG nColorSpaceType /*IN*/, ULONG nFrameWidth /*IN*/, ULONG nFrameHeight /*IN*/, ULONG nFrames, PVOID* ppFramePool ) __attribute__ ((deprecated));
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_GET_FRAME_BUFFER(PVOID pFramePool, BYTE** ppFrameBuffer /*IN*/, ULONG* pFrameBufferSize ) __attribute__ ((deprecated));
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_DESTROY_FRAME_POOL(PVOID pFramePool ) __attribute__ ((deprecated));
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_COPY_VIDEO_FRAME(BYTE * pSrcFrameBuffer /*IN*/, ULONG nSrcFrameBufferLen /*IN*/, BYTE * pDstFrameBuffer, ULONG nDstFrameBufferLen);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_SET_NATIVE_AUDIO_RENDERER_VOLUME(UINT nSoundNum /*IN*/, ULONG nVolume /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_GET_NATIVE_AUDIO_RENDERER_VOLUME(UINT nSoundNum /*IN*/, ULONG* pVolume /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_REGISTER_MOTION_DETECT_CALLBACK(PVOID pVDAHandle /*IN*/, PF_MOTION_DETECT_CALLBACK pCB /*IN*/, PVOID pUserData /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_CREATE_MOTION_MONITOR(PVOID *pVDAHandle /*OUT*/, ULONG nFrameWidth /*IN*/, ULONG nFrameHeight /*IN*/, ULONG VdaAlg /*IN*/, ULONG *nBlockWidth /*OUT*/, ULONG *nBlockHeight /*OUT*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_DESTROY_MOTION_MONITOR(PVOID pVDAHandle /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_START_MOTION_MONITOR(PVOID pVDAHandle /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_STOP_MOTION_MONITOR(PVOID pVDAHandle /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_SET_MOTION_DETECT_BUFFER(PVOID pVDAHandle /*IN*/, BYTE * pFrameBuffer /*IN*/, ULONG nFrameBufferLen /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_SET_MOTION_PROPERTY(PVOID pVDAHandle /*IN*/, ULONG nVdaIntvl /*IN*/, ULONG nBgUpSrcWgt /*IN*/, ULONG nSadTh /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_GET_MOTION_PROPERTY(PVOID pVDAHandle /*IN*/, ULONG *nVdaIntvl /*OUT*/, ULONG *nBgUpSrcWgt /*OUT*/, ULONG *nSadTh /*OUT*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_REGISTER_HDMI_SINK_CALLBACK(PF_HDMI_SINK_CALLBACK pCB /*IN*/, PVOID pUserData /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_GET_HDMI_SINK_CAPS(PBYTE pData, ULONG nBytes);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_HI_GET_HDMI_SINK_EDID(PBYTE pData, ULONG nBytes);

#ifdef __cplusplus
}
#endif

#endif // MOCK_QCAP_HI3531A_H
