#ifndef MOCK_QCAP_CCVT_H
#define MOCK_QCAP_CCVT_H

#include "qcap_mock_common.h"

#ifdef __cplusplus
extern "C"
{
#endif

// Function Declarations
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_CREATE_CCVT(ULONG nSrcW /*IN*/, ULONG nSrcH /*IN*/, ULONG nSrcColorSpaceType, ULONG nCropX /*IN*/, ULONG nCropY /*IN*/, ULONG nCropW /*IN*/, ULONG nCropH, ULONG nDstW /*IN*/, ULONG nDstH /*IN*/, ULONG nDstColorSpaceType, PVOID* ppCCVT);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_DESTROY_CCVT(PVOID pCCVT);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_START_CCVT(PVOID pCCVT);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_STOP_CCVT(PVOID pCCVT);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_REGISTER_VIDEO_CCVT_CALLBACK(PVOID pCCVT /*IN*/, PF_VIDEO_CCVT_CALLBACK pCB /*IN*/, PVOID pUserData /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_SET_VIDEO_CCVT_UNCOMPRESSION_BUFFER(PVOID pCCVT /*IN*/, BYTE * pFrameBuffer /*IN*/, ULONG nFrameBufferLen /*IN*/);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_SET_CCVT_CUSTOM_PROPERTY(PVOID pCCVT /*IN*/, ULONG nProperty, BYTE* pValue, ULONG nBytes);
QCAP_EXT_API QRESULT QCAP_EXPORT QCAP_GET_CCVT_CUSTOM_PROPERTY(PVOID pCCVT /*IN*/, ULONG nProperty, BYTE* pValue, ULONG nBytes);

#ifdef __cplusplus
}
#endif

#endif // MOCK_QCAP_CCVT_H
